### ISSUE TITLE
Pipboy Level Up/Perk Tree Crash

### ISSUE THREAD

**Issue by SPAHARA** [Rage-GitHub/Atomic-Warfare#2]
## What Issue is Occurring?
When I try to level up using the Pipboy, my game crashes.

## Where/When/How is This Issue Happening?
When I try to level up (attempting to access the perk screen) using the Pipboy, my game crashes. Location does not matter as it will occur in every location.

## Have You Modified The Modlist In Anyway?
[x ] Yes, I've edited it somewhat
I added TruBy9 Ultrawidescreen & Improved Rainbox

## Were You Able to Replicate This Issue?
[x ] Yes, I've successfully replicated the issue
The issue was replicated after a clean install of both Fallout 4 (Steam) and the Modlist via Wabbajack.

## Other Information
**Modlist Version**
1.1.0

**Game Version*
Latest 

**Is The Modlist Installed on the Same Drive?**
[x ] Yes, it's installed in the same drive

**Is Your Game Installation Outside of Protected Folders, I.E. Program Files (x86)?**
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
[ x] Yes, it's installed in the same drive

NOTE: The following are my specs:
Processor	11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz   2.50 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
NVIDIA GeForce RTX 3060 Ti

Not sure why the bug is occurring, I can play the game normally otherwise but if I try to access the Perk tree from the Pipboy it just crashes my game.

[crash-2022-08-10-07-14-17.log](https://github.com/Rage-GitHub/Atomic-Warfare/files/9297949/crash-2022-08-10-07-14-17.log)

**Comment by Rage-GitHub** [comment]
Potentially an issue regarding the Ultrawide mod. Test without and see if the issue still replicates.

**Comment by SPAHARA** [comment]
Ok, so I figured out the problem. TRUBY9 ULTRAWIDESCREEN mod is
incompatable with LevelUpMenuEx, there is a fix on Nexus simply called
"TRUBY9 ULTRAWIDESCREEN LevelUpMenuEx compatibility fix". I still have some
character stretching in 21x9 but I'll try and tweak. So far the Pipboy is
good, it's just an issue with FallUI.

Cheers
Shane

**Comment by SPAHARA** [comment]
That fixed the problem for sure. I should have tried that in retrospect. I
will test the other ultrawide UI mods separately and see if any work.

Cheers
Shane
