### ISSUE TITLE
[REQUEST] Damn Apocalypse Patches/Mods That Work Well In Tandem/etc.

### ISSUE THREAD

**Issue by YourFriendFaust** [Rage-GitHub/Atomic-Warfare#4]
Tons of different weapons and other patches/Raider Overhaul/Raiders Extended/Metro Gas Masks/etc. (https://www.nexusmods.com/fallout4/mods/61815?tab=description) ((I also suggest on DA's page the patch they provide for the DOOMBASED Pack))

Backpack consistency and rebalance (https://www.nexusmods.com/fallout4/mods/63253) ((Not technically a Damn Apocalypse exclusive patch but also something nice by Diacute is this great merge and rebalance of a few backpack mods so the world isn't so bloated by them and they are more consistent in their features and stats. Modular as well so you take what mods you want but they work in tandem wonderfully))

Damn Apocalypse Hunting/Harvesting Patches/Script (https://www.nexusmods.com/fallout4/mods/61424) ((I'm suggesting this over Hunter of the Commonwealth simply because of the ease of compatibility across not only DA but also other creature mods you have implemented/might implement in the future))

Hunter of the Commonwealth DA Patch (https://www.nexusmods.com/fallout4/mods/58166) ((Self explanatory though again I'd recommend above's solution instead since it provides more overall compatibility with only minimal loss in features, I do love Hunter of the Commonwealth and played with it in the past but I find DA's perfectly suitable in my opinion))

Some different consumables/specifically Wasteland Imports (https://www.nexusmods.com/fallout4/mods/61813) ((Since you seem to be adding in a lot of Fallout legacy-esque FO3/FNV content I am listing this though I suggest the MRE and CHEF addons from here as well as they all fit very well and have Immersive Animation Framework compatibility too))

Lore Friendly Names for MAIM items (https://www.nexusmods.com/fallout4/mods/61544?tab=description) ((It's nothing crazy and it's meant for the regular version of MAIM, not lite, but it's a nice touch and also speaking of MAIM if you ever add the radiation module from DA they have a nice patch for it too on their main page))

A complex sorter INI for DA (https://www.nexusmods.com/fallout4/mods/61814) ((Self explanatory though it might not be needed, thought I would make it aware to you either way))

Multiple weather patches (https://www.nexusmods.com/fallout4/mods/61186) ((If you end up implementing the DA rads module/a weather mod into the list, personally I've always leaned more towards Polluted or Calamity but that's just because I like things to be a bit more dark and apocalyptic though I have used NAC quite a bit and the rest are wonderful choices too)) 

I also highly suggest on DA's page the patches they provide for some of the mods you have here already so they fall in line with it, patches for Miami Misadventures, Point Lookout, Immersive Animation Framework, etc.

**Comment by Rage-GitHub** [comment]
Chosen mods have been added into the Modlist, see changelogs.
