### ISSUE TITLE
[REQUEST] Some small (one not so much) mods

### ISSUE THREAD

**Issue by TheOneHP** [Rage-GitHub/Atomic-Warfare#5]
**Mutant Menagerie - Strange Noises - Gun for Hire Quest Integration**
https://www.nexusmods.com/fallout4/mods/53793

**Improved - Animated Accessible Backpack (Stand Alone)**
https://www.nexusmods.com/fallout4/mods/58032

**No Case Unsolved - More Valentine Case Files**
https://www.nexusmods.com/fallout4/mods/58654

**Boston Unsealed and More (B.U.M.)**
https://www.nexusmods.com/fallout4/mods/60463

**Ryn's Fallout 4**
https://www.nexusmods.com/fallout4/mods/60426

**Sim Settlements - Three In One**
https://www.nexusmods.com/fallout4/mods/21872

**Leaders Of The Commonwealth - A Sim Settlements Add-on**
https://www.nexusmods.com/fallout4/mods/30495

**First-Person Swimming Animations**
https://www.nexusmods.com/fallout4/mods/62123

**HiPoly Faces REDUX (Seamless Kit - CBBE - TWB - FG)**
https://www.nexusmods.com/fallout4/mods/58950

Remove Dogmeat's Whining Audio
https://www.nexusmods.com/fallout4/mods/380

Immersive Dogmeat - Smart - Silent - Sneaky
https://www.nexusmods.com/fallout4/mods/34128

Everyone's Best Friend (Dogmeat and Companion At Same Time - No Console - No Hack)
https://www.nexusmods.com/fallout4/mods/13459

**Comment by Rage-GitHub** [comment]
I am considering using and implementing Ryn's Fallout 4 after the amazing success their mods have had in Fable Lore. I am very excited to try their work out in Fallout 4 so keep an eye on that. However, for the rest of the mods I'm not sure I will entirely add them just for convenience sake. Everyone's Best Friend though will be added.

**Comment by Rage-GitHub** [comment]
Some select mods were added in 1.6.0, see the [changelogs](https://github.com/Rage-GitHub/Atomic-Warfare/wiki/Changelogs#version-160) for those mods.
